Study Session PreStudy
Noah231515/MemUp pull request #47
Opened 2021-06-03 22:44 UTC by AndrewB21

## Changes

- Introduces the Study, PreStudy, and StudyGame components where Study acts as the parent to and link between the PreStudy and StudyGame components.
- Allows users to change the options of their study session in the pre study screen (size, type, and selected course)
- PreStudy displays a word table with the selected words for the session. At this time it selects words starting at index zero and going up to index sessionSize - 1. In the future we'll want to select words based on scheduling information.
- Modifies the WordTable component to better fit the pre study screen, allowing the headers and editing options to be hidden (they are normally displayed on the course details page), and allowing answers to be displayed or hidden. By default the are hidden on the pre study screen and displayed on the course details page.

2021-06-03 23:31 UTC, Noah231515 commented on ClientApp/src/app/courses/word-table/word-table.component.html
> +
remove line 40 and 39

2021-06-03 23:31 UTC, Noah231515 commented on ClientApp/src/app/courses/word-table/word-table.component.css
> +}
new line

2021-06-03 23:31 UTC, Noah231515 commented on ClientApp/src/app/courses/word-table/word-table.component.html
> +                        >
```suggestion
                        <span
                            *ngIf="sentence.sentenceText != null
                            && sentence.sentenceType.type != 'Furigana'"
                        >
```

2021-06-03 23:31 UTC, Noah231515 commented on ClientApp/src/app/courses/word-table/word-table.component.html
> +                        >
Not a huge fan of string comparisions in templates. Can you make all of these comparisons comparisons to constant strings? especially if you use them elsewhere, then that should live in a constants file somewhere like `sentance-type-constant.ts` f.ex

2021-06-03 23:31 UTC, Noah231515 commented on ClientApp/src/app/courses/word-table/word-table.component.html
> +</div>
new line

2021-06-03 23:31 UTC, Noah231515 commented on ClientApp/src/app/courses/word-table/word-table.component.html
> +                        sentence.sentenceType.type != 'Furigana'"
same formatting change as above

2021-06-03 23:31 UTC, Noah231515 commented on ClientApp/src/app/courses/word-table/word-table.component.ts
> +  public checkForAdditionalTableData(pageEvent: PageEvent) {
method comment

2021-06-03 23:31 UTC, Noah231515 commented on ClientApp/src/app/courses/word-table/word-table.component.ts
> +  public toggleWordStatus(word: Word) {
method comment

2021-06-03 23:31 UTC, Noah231515 commented on ClientApp/src/app/courses/word-table/word-table.component.ts
> +  public changeSelectedTableAction(event: any) {
method comment

2021-06-03 23:31 UTC, Noah231515 commented on ClientApp/src/app/courses/word-table/word-table.component.ts
> +  public toggleVisibility(word: Word, targetArrayType: string, iconRef: any) {
method comment

2021-06-03 23:31 UTC, Noah231515 commented on ClientApp/src/app/courses/word-table/word-table.component.ts
> +  public changeVisibilityStatus(elementRef: ElementRef, iconRef: any) {
method comment

2021-06-03 23:31 UTC, Noah231515 commented on ClientApp/src/app/courses/word-table/word-table.component.ts
> +  public executeTableAction() {
method comment

2021-06-03 23:31 UTC, Noah231515 commented on ClientApp/src/app/courses/word-table/word-table.component.ts
> +  @Input() public dataSource: Word[];
```suggestion
  @Input() public wordDataSource: Word[];
```

2021-06-03 23:31 UTC, Noah231515 commented on ClientApp/src/app/study/pre-study/pre-study.component.css
> +}
newline

2021-06-03 23:31 UTC, Noah231515 commented on ClientApp/src/app/study/pre-study/pre-study.component.ts
> +    try {
It would be cleaner to have three separate methods to handle the updating of each thing. f.ex, `updateSize` `updateCourse` `updateType`

2021-06-03 23:31 UTC, Noah231515 commented on ClientApp/src/app/study/study-game/study-game.component.html
> +<p>study-game works!</p>
```suggestion

```

2021-06-03 23:31 UTC, Noah231515 commented on ClientApp/src/app/study/study.component.html
> +    *ngIf="isPreStudy"></app-pre-study>
```suggestion
<app-pre-study 
    *ngIf="isPreStudy"
    [allCourses]="courseList"
    [studyOptions]="selectedOptions"
    (updateCourse)="updateCourse($event)"
    (updateSize)="updateSessionSize($event)"
    (updateType)="updateSessionType($event)"
 ></app-pre-study>
```

2021-06-03 23:31 UTC, Noah231515 commented on ClientApp/src/app/study/study.component.html
> +<app-study-game [course]="selectedCourse" *ngIf="isStudyGame"></app-study-game>
newline

2021-06-03 23:31 UTC, Noah231515 commented on ClientApp/src/app/study/pre-study/pre-study.component.ts
> +    try {
don't forget to add method comments

2021-06-03 23:31 UTC, Noah231515 commented on ClientApp/src/app/study/study.component.ts
> +  public changeSessionMode() {
method comment

2021-06-03 23:31 UTC, Noah231515 commented on ClientApp/src/app/study/study.component.ts
> +  public updateSessionSize(newSize: number) {
method comment

2021-06-03 23:31 UTC, Noah231515 commented on ClientApp/src/app/study/study.component.ts
> +  public updateSessionType(newType: string) {
method comment

2021-06-03 23:31 UTC, Noah231515 commented on ClientApp/src/app/user-dashboard/course-summary-card/course-summary-card.component.css
> +}
newline

2021-06-03 23:31 UTC, Noah231515 commented on ClientApp/src/styles.css
> +}
newline

2021-06-04 00:41 UTC, AndrewB21 commented
All requested changes should be good to go!

2021-06-05 13:03 UTC, Noah231515 requested changes

2021-06-05 13:03 UTC, Noah231515 commented on ClientApp/src/app/constants/sentence-type.constants.ts
> +    english: 'English',
```suggestion
    ENGLISH: 'English',
```
By convention these should be all caps

2021-06-05 16:51 UTC, AndrewB21 commented on ClientApp/src/app/constants/sentence-type.constants.ts
> +    english: 'English',
Fixed!

2021-06-08 23:43 UTC, merged